config/routes.rb
MCToolkit::Application.routes.draw do

  resources :analysts

  resources :themes

  resources :attachments

  resources :observations

  resources :events

  resources :ctos

  resources :units

  resources :exercises

  resources :current_exercises

  resources :homes

  devise_for :mcts

  resources :roles

  resources :users

  resources :mcts

  root :to => "homes#index"

  

end

app/models/analyst.rb
class Analyst
  include Mongoid::Document
end

app/models/attachment.rb
class Attachment
  include Mongoid::Document
  field :descript, type: String
  mount_uploader :doc, AttachmentUploader
end

app/models/cto.rb
class Cto
  include Mongoid::Document
  field :cto, type: String
  embedded_in :unit
end

app/models/current_exercise.rb
class CurrentExercise
  include Mongoid::Document
  field :name, type: String
end

app/models/exercise.rb
class Exercise
  include Mongoid::Document
  field :name, type: String
  field :start, type: Date
  field :end, type: Date
  embeds_many :units
  accepts_nested_attributes_for :units, :allow_destroy => true
  embeds_many :observations
  accepts_nested_attributes_for :observations, :allow_destroy => true
  embeds_many :themes
  accepts_nested_attributes_for :themes, :allow_destroy => true
end

app/models/home.rb
class Home
  include Mongoid::Document
end

app/models/mct.rb
class Mct
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              :type => String, :default => ""
  field :encrypted_password, :type => String, :default => ""

  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  ## Confirmable
  # field :confirmation_token,   :type => String
  # field :confirmed_at,         :type => Time
  # field :confirmation_sent_at, :type => Time
  # field :unconfirmed_email,    :type => String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,       :type => Time

  ## Token authenticatable
  # field :authentication_token, :type => String
  field :lastname, type: String
  field :firstname, type: String
  field :rank, type: String
  field :role, type: String
  field :unit_assign, type: String
end

app/models/observation.rb
class Observation
  include Mongoid::Document
  field :dtg, type: Time
  field :oct, type: String
  field :obs, type: String
  field :recommend, type: String
  field :aar_ques, type: String
  field :unit, type: String
  field :theme, type: String
  embeds_many :attachments
  accepts_nested_attributes_for :attachments, :allow_destroy => true
  embedded_in :exercise
end

app/models/role.rb
class Role
  include Mongoid::Document
  field :title, type: String
end

app/models/theme.rb
class Theme
  include Mongoid::Document
  field :name, type: String
  field :notes, type: String
  embedded_in :exercise
end

app/models/unit.rb
class Unit
  include Mongoid::Document
  field :unit_name, type: String
  embeds_many :ctos
  accepts_nested_attributes_for :ctos, :allow_destroy => true
  embedded_in :exercise
end

app/models/user.rb
class User
  include Mongoid::Document
  field :username, type: String
  field :password, type: String
  field :lastname, type: String
  field :firstname, type: String
  field :rank, type: String
  field :role, type: String
  store_in collection: 'users'
end

app/controllers/mcts_controller.rb
class MctsController < ApplicationController
  before_filter :admin_user, :authenticate_mct!, :except => [:new]
  before_action :set_mct, only: [:show, :edit, :update, :destroy]

  # GET /mcts
  # GET /mcts.json
  def index
    @mcts = Mct.all
  end

  # GET /mcts/1
  # GET /mcts/1.json
  def show
  end

  # GET /mcts/new
  def new
    @mct = Mct.new
    @dropdown_options = Role.all
    @ex_list = Array.new
    Exercise.all.each do |ex|
      @ex_list.push(ex.name)
    end
    ex = Exercise.find_by(name: CurrentExercise.first.name)
    if ex != nil
      units = ex.units
      @unit_list = Array.new
      units.each do |unit|
        @unit_list.push(unit.unit_name)
      end
    else
      @unit_list = nil
    end
  end

  # GET /mcts/1/edit
  def edit
    @dropdown_options = Role.all
    @ex_list = Array.new
    Exercise.all.each do |ex|
      @ex_list.push(ex.name)
    end
    ex = Exercise.find_by(name: CurrentExercise.first.name)
    if ex != nil
      @units = ex.units
      @unit_list = Array.new
      @units.each do |unit|
        @unit_list.push(unit.unit_name)
      end
    else
      @unit_list = nil
    end
  end

  # POST /mcts
  # POST /mcts.json
  def create
    @mct = Mct.new(mct_params)

    respond_to do |format|
      if @mct.save
        format.html { redirect_to @home, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @mct }
      else
        format.html { render action: 'new' }
        format.json { render json: @mct.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mcts/1
  # PATCH/PUT /mcts/1.json
  def update
    if mct_params[:password].blank?
      mct_params.delete(:password)
      mct_params.delete(:password_confirmation)
    end

    successfully_updated = if needs_password?(@mct, mct_params)
                             @mct.update(mct_params)
                           else
                             @mct.update_without_password(mct_params)
                           end
    respond_to do |format|
      # params[:mct].delete(:current_password)
      if successfully_updated
      # if @mct.update_without_password(mct_params)
        format.html { redirect_to @mct, notice: 'Mct was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @mct.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mcts/1
  # DELETE /mcts/1.json
  def destroy
    @mct.destroy
    respond_to do |format|
      format.html { redirect_to mcts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mct
      @mct = Mct.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mct_params
      #params[:mct]
      params.require(:mct).permit(:email, :lastname, :firstname, :rank, :role, :unit_assign)
    end

    # https://github.com/plataformatec/devise/wiki/How-To%3a-Allow-users-to-edit-their-account-without-providing-a-password
    def needs_password?(mct, params)
      params[:password].present?
    end

    def admin_user
      if mct_signed_in?
        if current_mct.role != 'admin'
          redirect_to homes_path
        end
      end

    end
end

app/helpers/analysts_helper.rb
module AnalystsHelper
end

app/helpers/ctos_helper.rb
module CtosHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/homes_helper.rb
module HomesHelper


end

app/helpers/mcts_helper.rb
module MctsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/mcts/_form.html.erb
<%= form_for(@mct) do |f| %>
  <% if @mct.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mct.errors.count, "error") %> prohibited this mct from being saved:</h2>

      <ul>
      <% @mct.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table>
    <tr>
	  <td style="padding-top: 3px; text-align: right; padding-right: 5px; padding-bottom: 2px"><%= f.label text='Email:' %></td>
      <td><%= f.text_field :email %></td>
	</tr>
	<tr>
	  <td style="text-align: right; padding-right: 5px; padding-bottom: 2px; padding-top: 3px"><%= f.label text='Last Name:', style: 'vertical-align: middle' %></td>
      <td><%= f.text_field :lastname %></td>
	</tr>
	<tr>
	  <td style="text-align: right; padding-right: 5px; padding-bottom: 2px; padding-top: 3px"><%= f.label text='First Name:' %></td>
      <td><%= f.text_field :firstname %></td>
	</tr>
	<tr>
	  <td style="text-align: right; padding-right: 5px; padding-bottom: 2px; padding-top: 3px"><%= f.label text='Rank:' %></td>
      <td><%= f.text_field :rank %></td>
	</tr>
	<tr>
	  <td style="text-align: right; padding-right: 5px; padding-bottom: 2px; padding-top: 3px"><%= f.label text='Assigned Unit:' %></td>
      <td><%= f.collection_select :unit_assign, @units, :unit_name, :unit_name, {:include_blank => :unit_assign} %></td>
	</tr>
	<tr>
	  <td style="text-align: right; padding-right: 5px; padding-bottom: 2px; padding-top: 3px"><%= f.label text='Role:' %></td>
      <td><%= f.collection_select :role, $rolelist, :title, :title %></td>
    </tr>
  </table>
  <br/>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mcts/edit.html.erb
<h1>Edit User</h1>

<%= render 'form' %>

<%= link_to 'Show', @mct %>
<% if current_mct.role == 'admin' %>
    <%= link_to 'Back', mcts_path %>
<% else %>
    <%= link_to 'Back', homes_path %>
<% end %>

app/views/mcts/index.html.erb
<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading"><h1>Users</h1></div>
  <table class="table table-bordered">
    <thead>
    <tr>
      <th>Email</th>
      <th>Last name</th>
      <th>First name</th>
      <th>Rank</th>
      <th>Role</th>
      <th>Actions</th>
    </tr>
    </thead>

    <tbody>
    <% @mcts.each do |mct| %>
        <tr>
          <td><%= mct.email %></td>
          <td><%= mct.lastname %></td>
          <td><%= mct.firstname %></td>
          <td><%= mct.rank %></td>
          <td><%= mct.role %></td>
          <td>
            <% if current_mct.role != 'admin' %>
                <%= link_to edit_mct_registration_path(mct), :class => "btn btn-xxs btn-default" do %><i class="glyphicon glyphicon-pencil"></i> Edit<% end %>
            <% end %>
            <% if current_mct.role == 'admin' %>
                <%= link_to edit_mct_path(mct), :class => "btn btn-xxs btn-default" do %><i class="glyphicon glyphicon-pencil"></i> Edit<% end %>
            <% end %>
            <%= link_to mct, method: :delete, data: { confirm: 'Are you sure?' }, style: 'color: white !important', :class => "btn btn-xxs btn-danger" do %><i class="glyphicon glyphicon-trash"></i> Delete<% end %>

          </td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

<br>

<%= link_to new_mct_path, :class => "btn btn-xs btn-default" do %><i class="glyphicon glyphicon-plus"></i> New User<% end %>

app/views/mcts/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<% if mct_signed_in? %>
    <% if current_mct.role == 'admin' %>
        <%= link_to 'Back', mcts_path %>
    <% else %>
        <%= link_to 'Back', homes_path %>
    <% end %>
<% end %>

app/views/mcts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_mct_path(@mct) %> |
<%= link_to 'Back', mcts_path %>