config/routes.rb
MCToolkit::Application.routes.draw do

  resources :analysts

  resources :themes

  resources :attachments

  resources :observations

  resources :events

  resources :ctos

  resources :units

  resources :exercises

  resources :current_exercises

  resources :homes

  devise_for :mcts

  resources :roles

  resources :users

  resources :mcts

  root :to => "homes#index"

  

end

app/models/analyst.rb
class Analyst
  include Mongoid::Document
end

app/models/attachment.rb
class Attachment
  include Mongoid::Document
  field :descript, type: String
  mount_uploader :doc, AttachmentUploader
end

app/models/cto.rb
class Cto
  include Mongoid::Document
  field :cto, type: String
  embedded_in :unit
end

app/models/current_exercise.rb
class CurrentExercise
  include Mongoid::Document
  field :name, type: String
end

app/models/exercise.rb
class Exercise
  include Mongoid::Document
  field :name, type: String
  field :start, type: Date
  field :end, type: Date
  embeds_many :units
  accepts_nested_attributes_for :units, :allow_destroy => true
  embeds_many :observations
  accepts_nested_attributes_for :observations, :allow_destroy => true
  embeds_many :themes
  accepts_nested_attributes_for :themes, :allow_destroy => true
end

app/models/home.rb
class Home
  include Mongoid::Document
end

app/models/mct.rb
class Mct
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              :type => String, :default => ""
  field :encrypted_password, :type => String, :default => ""

  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  ## Confirmable
  # field :confirmation_token,   :type => String
  # field :confirmed_at,         :type => Time
  # field :confirmation_sent_at, :type => Time
  # field :unconfirmed_email,    :type => String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,       :type => Time

  ## Token authenticatable
  # field :authentication_token, :type => String
  field :lastname, type: String
  field :firstname, type: String
  field :rank, type: String
  field :role, type: String
  field :unit_assign, type: String
end

app/models/observation.rb
class Observation
  include Mongoid::Document
  field :dtg, type: Time
  field :oct, type: String
  field :obs, type: String
  field :recommend, type: String
  field :aar_ques, type: String
  field :unit, type: String
  field :theme, type: String
  embeds_many :attachments
  accepts_nested_attributes_for :attachments, :allow_destroy => true
  embedded_in :exercise
end

app/models/role.rb
class Role
  include Mongoid::Document
  field :title, type: String
end

app/models/theme.rb
class Theme
  include Mongoid::Document
  field :name, type: String
  field :notes, type: String
  embedded_in :exercise
end

app/models/unit.rb
class Unit
  include Mongoid::Document
  field :unit_name, type: String
  embeds_many :ctos
  accepts_nested_attributes_for :ctos, :allow_destroy => true
  embedded_in :exercise
end

app/models/user.rb
class User
  include Mongoid::Document
  field :username, type: String
  field :password, type: String
  field :lastname, type: String
  field :firstname, type: String
  field :rank, type: String
  field :role, type: String
  store_in collection: 'users'
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: [:show, :edit, :update, :destroy]

  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
        format.json { render action: 'show', status: :created, location: @role }
      else
        format.html { render action: 'new' }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def role_params
      params.require(:role).permit(:title)
    end
end

app/helpers/analysts_helper.rb
module AnalystsHelper
end

app/helpers/ctos_helper.rb
module CtosHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/homes_helper.rb
module HomesHelper


end

app/helpers/mcts_helper.rb
module MctsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/roles/_form.html.erb
<%= form_for(@role) do |f| %>
  <% if @role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
      <% @role.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/roles/edit.html.erb
<h1>Editing role</h1>

<%= render 'form' %>

<%= link_to 'Show', @role %> |
<%= link_to 'Back', roles_path %>

app/views/roles/index.html.haml
.panel.panel-default
  / Default panel contents
  .panel-heading
    %h1 User Roles
  / Table
  %table.table
    %thead
      %tr
        %th Title
        %th Actions
    %tbody
      - @roles.each do |role|
        %tr
          %td= role.title
          %td
            = link_to edit_role_path(role), :class => "btn btn-xs" do
              %i.glyphicon.glyphicon-pencil
              Edit
            = link_to role, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-xs" do
              %i.glyphicon.glyphicon-trash
              Delete
%br/
= link_to new_role_path, :class => "btn btn-xs" do
  %i.glyphicon.glyphicon-plus
  New Role

app/views/roles/new.html.erb
<h1>New role</h1>

<%= render 'form' %>

<%= link_to 'Back', roles_path %>

app/views/roles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @role.title %>
</p>

<%= link_to 'Edit', edit_role_path(@role) %> |
<%= link_to 'Back', roles_path %>